// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Debug logging for environment variables
console.log('=== SUPABASE CONFIGURATION DEBUG ===');
console.log('VITE_SUPABASE_URL:', SUPABASE_URL);
console.log('VITE_SUPABASE_ANON_KEY:', SUPABASE_ANON_KEY ? 'Present (length: ' + SUPABASE_ANON_KEY.length + ')' : 'Missing');
console.log('All env vars:', import.meta.env);

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('❌ Missing Supabase environment variables!');
  console.error('VITE_SUPABASE_URL:', SUPABASE_URL);
  console.error('VITE_SUPABASE_ANON_KEY:', SUPABASE_ANON_KEY ? 'Present' : 'Missing');
} else {
  console.log('✅ Environment variables loaded successfully');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co', 
  SUPABASE_ANON_KEY || 'placeholder-key', 
  {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});

// Add error logging for auth operations
supabase.auth.onAuthStateChange((event, session) => {
  console.log('🔐 Auth state change:', event, session ? 'User logged in' : 'User logged out');
  if (event === 'SIGNED_IN') {
    console.log('✅ User signed in successfully');
  } else if (event === 'SIGNED_OUT') {
    console.log('❌ User signed out');
  } else if (event === 'TOKEN_REFRESHED') {
    console.log('🔄 Token refreshed');
  } else if (event === 'USER_UPDATED') {
    console.log('👤 User updated');
  }
});